services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8085:8080
    restart: always
    volumes:
      - storage:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
volumes:
  storage:
    driver: local