services:
  server:
    build:
      context: .
      target: final
    ports:
      - 12345:12345
    restart: always
    volumes:
      - storage:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
volumes:
  storage:
    driver: local